ifeq ($(CONFIG_OF),y)

ifeq ($(CONFIG_SEC_J3_PROJECT),y)
	ifeq ($(CONFIG_MACH_J3LTE_CHN_CTC),y)
		dtb-y += msm8916-sec-j3lte-chnctc-r00.dtb
		dtb-y += msm8916-sec-j3lte-chnctc-r02.dtb
		dtb-y += msm8916-sec-j3lte-chnctc-r05.dtb
	else ifeq ($(CONFIG_MACH_J3LTE_USA_SPR),y)
		dtb-y += msm8916-sec-j3lte-spr-r00.dtb
		dtb-y += msm8916-sec-j3lte-spr-r01.dtb
	else ifeq ($(CONFIG_MACH_J3LTE_USA_VZW),y)
		dtb-y += msm8916-sec-j3lte-vzw-r00.dtb
		dtb-y += msm8916-sec-j3lte-vzw-r02.dtb
		dtb-y += msm8916-sec-j3lte-vzw-r03.dtb
	else ifeq ($(CONFIG_MACH_J3LTE_USA_USC),y)
		dtb-y += msm8916-sec-j3lte-usc-r00.dtb
	else ifeq ($(CONFIG_MACH_J3LTE_KOR_OPEN),y)
		dtb-y += msm8916-sec-j3lte-kor-r03.dtb
	endif
endif

ifeq ($(CONFIG_SEC_GTEL_PROJECT),y)
	ifeq ($(CONFIG_MACH_GTEL_USA_VZW),y)
		dtb-y += msm8916-sec-gtel-vzw-r00.dtb
		dtb-y += msm8916-sec-gtel-vzw-r01.dtb
		dtb-y += msm8916-sec-gtel-vzw-r02.dtb
		dtb-y += msm8916-sec-gtel-vzw-r03.dtb
		dtb-y += msm8916-sec-gtel-vzw-r04.dtb
		dtb-y += msm8916-sec-gtel-vzw-r05.dtb
	else ifeq ($(CONFIG_MACH_GTELWIFI_USA_OPEN),y)
		dtb-y += msm8916-sec-gtelwifi-usa-r00.dtb
		dtb-y += msm8916-sec-gtelwifi-usa-r01.dtb
		dtb-y += msm8916-sec-gtelwifi-usa-r02.dtb
		dtb-y += msm8916-sec-gtelwifi-usa-r03.dtb
		dtb-y += msm8916-sec-gtelwifi-usa-r04.dtb
		dtb-y += msm8916-sec-gtelwifi-usa-r05.dtb
	endif
endif

ifeq ($(CONFIG_SEC_FORTUNA_PROJECT),y)
	ifeq ($(CONFIG_MACH_FORTUNA_EUR_OPEN),y)
		dtb-y += msm8916-sec-fortuna-eur-r00.dtb
		dtb-y += msm8916-sec-fortuna-eur-r01.dtb
		dtb-y += msm8916-sec-fortuna-eur-r02.dtb
	else ifeq ($(CONFIG_MACH_FORTUNA3G_EUR),y)
		dtb-y += msm8916-sec-fortuna-r00.dtb
		dtb-y += msm8916-sec-fortuna-r01.dtb
		dtb-y += msm8916-sec-fortuna-r03.dtb
		dtb-y += msm8916-sec-fortuna-r04.dtb
		dtb-y += msm8916-sec-fortuna-r06.dtb
		dtb-y += msm8916-sec-fortuna-r07.dtb
		dtb-y += msm8916-sec-fortuna-r09.dtb
		dtb-y += msm8916-sec-fortuna-r11.dtb
	else ifeq ($(CONFIG_MACH_FORTUNAVE3G_EUR),y)
		dtb-y += msm8916-sec-fortuna-ve3g-r07.dtb
	else ifeq ($(CONFIG_MACH_FORTUNA_SEA_OPEN),y)
		dtb-y += msm8916-sec-fortuna-sea-r07.dtb
		dtb-y += msm8916-sec-fortuna-sea-r08.dtb
		dtb-y += msm8916-sec-fortuna-sea-r09.dtb
	else ifeq ($(CONFIG_MACH_FORTUNA_TFN),y)
		dtb-y += msm8916-sec-fortuna-tfn-r00.dtb
		dtb-y += msm8916-sec-fortuna-tfn-r02.dtb
	else ifeq ($(CONFIG_MACH_FORTUNA_USC),y)
		dtb-y += msm8916-sec-fortuna-usc-r00.dtb
		dtb-y += msm8916-sec-fortuna-usc-r01.dtb
		dtb-y += msm8916-sec-fortuna-usc-r03.dtb
	else ifeq ($(CONFIG_MACH_FORTUNA_TMO),y)
                dtb-y += msm8916-sec-fortuna-tmo-r00.dtb
                dtb-y += msm8916-sec-fortuna-tmo-r02.dtb
	else ifeq ($(CONFIG_MACH_FORTUNA_SPR),y)
                dtb-y += msm8916-sec-fortuna-spr-r00.dtb
	else ifeq ($(CONFIG_MACH_FORTUNA_ACG),y)
                dtb-y += msm8916-sec-fortuna-acg-r00.dtb
	else ifeq ($(CONFIG_MACH_FORTUNA_CMCC),y)
		dtb-y += msm8916-sec-fortuna-r00.dtb
		dtb-y += msm8916-sec-fortuna-r01.dtb
		dtb-y += msm8916-sec-fortuna-r03.dtb
		dtb-y += msm8916-sec-fortuna-r04.dtb
		dtb-y += msm8916-sec-fortuna-r06.dtb
		dtb-y += msm8916-sec-fortuna-r07.dtb
		dtb-y += msm8916-sec-fortuna-r09.dtb
		dtb-y += msm8916-sec-fortuna-r10.dtb
		dtb-y += msm8916-sec-fortuna-r11.dtb
	else ifeq ($(CONFIG_MACH_FORTUNA_CHN_ZT),y)
		dtb-y += msm8916-sec-fortuna-r00.dtb
		dtb-y += msm8916-sec-fortuna-r01.dtb
		dtb-y += msm8916-sec-fortuna-r03.dtb
		dtb-y += msm8916-sec-fortuna-r04.dtb
		dtb-y += msm8916-sec-fortuna-r06.dtb
		dtb-y += msm8916-sec-fortuna-r07.dtb
		dtb-y += msm8916-sec-fortuna-r09.dtb
		dtb-y += msm8916-sec-fortuna-r10.dtb
		dtb-y += msm8916-sec-fortuna-r11.dtb
	else ifeq ($(CONFIG_MACH_FORTUNA),y)
		dtb-y += msm8916-sec-fortuna-r00.dtb
		dtb-y += msm8916-sec-fortuna-r01.dtb
		dtb-y += msm8916-sec-fortuna-r03.dtb
		dtb-y += msm8916-sec-fortuna-r04.dtb
		dtb-y += msm8916-sec-fortuna-r06.dtb
		dtb-y += msm8916-sec-fortuna-r07.dtb
		dtb-y += msm8916-sec-fortuna-r09.dtb
		dtb-y += msm8916-sec-fortuna-r10.dtb
		dtb-y += msm8916-sec-fortuna-r11.dtb
        endif

endif

ifeq ($(CONFIG_SEC_ROSSA_PROJECT),y)
	ifeq ($(CONFIG_MACH_ROSSA_TMO),y)
		dtb-y += msm8916-sec-rossatmo-r00.dtb
	endif
endif

ifeq ($(CONFIG_SEC_XCOVER3_PROJECT),y)
	ifeq ($(CONFIG_MACH_XCOVER3_DCM),y)
		dtb-y += msm8916-sec-xcover3-dcm-r01.dtb
		dtb-y += msm8916-sec-xcover3-dcm-r02.dtb
		dtb-y += msm8916-sec-xcover3-dcm-r03.dtb
	endif
endif

ifeq ($(CONFIG_SEC_J1_PROJECT),y)
	ifeq ($(CONFIG_MACH_J1_VZW),y)
		dtb-y += msm8916-sec-j1vzw-r00.dtb
		dtb-y += msm8916-sec-j1vzw-r02.dtb
	endif
endif

ifeq ($(CONFIG_SEC_J1X_PROJECT),y)
	ifeq ($(CONFIG_MACH_J1XLTE_USA_SPR),y)
		dtb-y += msm8916-sec-j1xlte-spr-r00.dtb
	else ifeq ($(CONFIG_MACH_J1XLTE_USA_TFNVZW),y)
		dtb-y += msm8916-sec-j1xlte-tfnvzw-r00.dtb
	endif
endif

ifeq ($(CONFIG_SEC_J5X_PROJECT),y)
	ifeq ($(CONFIG_MACH_J5XLTE_CHN_CMCC),y)
		dtb-y += msm8916-sec-j5xlte-chn-r00.dtb
	else ifeq ($(CONFIG_MACH_J5XLTE_EUR_OPEN),y)
		dtb-y += msm8916-sec-j5xlte-eur-r00.dtb
		dtb-y += msm8916-sec-j5xlte-eur-r01.dtb
		dtb-y += msm8916-sec-j5xlte-eur-r02.dtb
		dtb-y += msm8916-sec-j5xlte-eur-r04.dtb
	else ifeq ($(CONFIG_MACH_J5XLTE_KOR_OPEN),y)
		dtb-y += msm8916-sec-j5xlte-kor-r01.dtb
		dtb-y += msm8916-sec-j5xlte-kor-r02.dtb
		dtb-y += msm8916-sec-j5xlte-kor-r04.dtb
	else ifeq ($(CONFIG_MACH_J5X3G_MEA_JV),y)
		dtb-y += msm8916-sec-j5x3g-mea-r00.dtb
		dtb-y += msm8916-sec-j5x3g-mea-r01.dtb
		dtb-y += msm8916-sec-j5x3g-mea-r02.dtb
		dtb-y += msm8916-sec-j5x3g-mea-r04.dtb
	else ifeq ($(CONFIG_MACH_J5XLTE_MEA_JV),y)
		dtb-y += msm8916-sec-j5xlte-mea-r00.dtb
		dtb-y += msm8916-sec-j5xlte-mea-r01.dtb
		dtb-y += msm8916-sec-j5xlte-mea-r02.dtb
		dtb-y += msm8916-sec-j5xlte-mea-r04.dtb
	else ifeq ($(CONFIG_MACH_J5XLTE_MEA_TUR),y)
		dtb-y += msm8916-sec-j5xlte-tur-r00.dtb
		dtb-y += msm8916-sec-j5xlte-tur-r01.dtb
		dtb-y += msm8916-sec-j5xlte-tur-r02.dtb
		dtb-y += msm8916-sec-j5xlte-tur-r04.dtb
	endif
endif

ifeq ($(CONFIG_SEC_J5_PROJECT),y)
	ifeq ($(CONFIG_MACH_J5LTE_EUR_OPEN),y)
		dtb-y += msm8916-sec-j5lte-eur-r00.dtb
		dtb-y += msm8916-sec-j5lte-eur-r01.dtb
		dtb-y += msm8916-sec-j5lte-eur-r05.dtb
	else ifeq ($(CONFIG_MACH_J53G_EUR_OPEN),y)
		dtb-y += msm8916-sec-j53g-eur-r00.dtb
		dtb-y += msm8916-sec-j53g-eur-r01.dtb
		dtb-y += msm8916-sec-j53g-eur-r02.dtb
		dtb-y += msm8916-sec-j53g-eur-r05.dtb
	else ifeq ($(CONFIG_MACH_J5LTE_CHN_CMCC),y)
		dtb-y += msm8916-sec-j5lte-chn-r00.dtb
		dtb-y += msm8916-sec-j5lte-chn-r01.dtb
	else ifeq ($(CONFIG_MACH_J5LTE_KOR_OPEN),y)
		dtb-y += msm8916-sec-j5lte-kor-r01.dtb
		dtb-y += msm8916-sec-j5lte-kor-r05.dtb
	else ifeq ($(CONFIG_MACH_J5LTE_LTN_DTV),y)
		dtb-y += msm8916-sec-j5lte-ltn-dtv-r04.dtb
		dtb-y += msm8916-sec-j5lte-ltn-dtv-r05.dtb
	else ifeq ($(CONFIG_MACH_J5YLTE_SEA_NZC),y)
		dtb-y += msm8916-sec-j5ylte-sea-r00.dtb
		dtb-y += msm8916-sec-j5ylte-sea-r01.dtb
		dtb-y += msm8916-sec-j5ylte-sea-r05.dtb
	endif
endif

ifeq ($(CONFIG_SEC_J5N_PROJECT),y)
	ifeq ($(CONFIG_MACH_J5NLTE_EUR_OPEN),y)
		dtb-y += msm8916-sec-j5nlte-eur-r04.dtb
		dtb-y += msm8916-sec-j5nlte-eur-r05.dtb
	endif
endif

ifeq ($(CONFIG_SEC_ON7N_PROJECT),y)
	ifeq ($(CONFIG_MACH_ON7NLTE_KOR_SKT),y)
		dtb-y += msm8916-sec-on7nlte-kor-r00.dtb
	endif
endif

dtb-$(CONFIG_ARCH_APQ8084) += apq8084-v1.0-old-pwr-grid-liquid.dtb \
	apq8084-v1.1-old-pwr-grid-liquid.dtb \
	apq8084-v1.1-liquid.dtb \
	apq8084-v1.0-old-pwr-grid-smb1357-cdp.dtb \
	apq8084-v1.1-old-pwr-grid-smb1357-cdp.dtb \
	apq8084-v1.1-smb1357-cdp.dtb \
	apq8084-v1.0-old-pwr-grid-smb1357-mtp.dtb \
	apq8084-v1.1-old-pwr-grid-smb1357-mtp.dtb \
	apq8084-v1.1-smb1357-mtp.dtb \
	apq8084-v1.0-old-pwr-grid-smb1359-mdm9x35-alt-mtp.dtb \
	apq8084-v1.1-old-pwr-grid-smb1359-mdm9x35-alt-mtp.dtb \
	apq8084-v1.1-smb1359-mdm9x35-alt-mtp.dtb \
	apq8084-old-pwr-grid-smb349-cdp.dtb \
	apq8084-old-pwr-grid-smb349-mtp.dtb \
	apq8084-v1.0-old-pwr-grid-smb1357-mdm9x35-alt-rcm.dtb \
	apq8084-v1.1-old-pwr-grid-smb1357-mdm9x35-alt-rcm.dtb \
	apq8084-v1.1-smb1357-mdm9x35-alt-rcm.dtb \
	apq8084-v1.0-old-pwr-grid-smb1357-mdm9x35-mtp.dtb \
	apq8084-v1.1-old-pwr-grid-smb1357-mdm9x35-mtp.dtb \
	apq8084-v1.1-smb1357-mdm9x35-mtp.dtb \
	apq8084-v1.0-old-pwr-grid-smb1357-mdm9x35-cdp.dtb \
	apq8084-v1.1-old-pwr-grid-smb1357-mdm9x35-cdp.dtb \
	apq8084-v1.1-smb1357-mdm9x35-cdp.dtb \
	apq8084-v1.0-old-pwr-grid-mdm9x35-alt-cdp.dtb \
	apq8084-v1.1-old-pwr-grid-mdm9x35-alt-cdp.dtb \
	apq8084-v1.1-mdm9x35-alt-cdp.dtb \
	apq8084-v1.1-sbc.dtb
dtb-$(CONFIG_ARCH_MSM8994) += msm8994-v1-sim.dtb \
	msm8994-rumi.dtb \
	msm8994-v1-cdp.dtb \
	msm8994-pmi8994-pm8004-v1-cdp.dtb \
	msm8994-v1-mtp.dtb \
	msm8994-pmi8994-pm8004-v1-mtp.dtb \
	msm8994-v1-liquid.dtb \
	msm8994-v1-fluid.dtb \
	apq8094-v1-cdp.dtb \
	apq8094-v1-mtp.dtb \
	apq8094-v1-liquid.dtb \
	apq8094-v1-fluid.dtb \
	apq8094-v1-dragonboard.dtb \
	msm8994-v2-sim.dtb \
	msm8994-v2-cdp.dtb \
	msm8994-pmi8994-pm8004-v2-cdp.dtb \
	msm8994-v2-mtp.dtb \
	msm8994-pmi8994-pm8004-v2-mtp.dtb \
	msm8994-v2-liquid.dtb \
	msm8994-v2-fluid.dtb \
	apq8094-v2-cdp.dtb \
	apq8094-v2-mtp.dtb \
	apq8094-v2-liquid.dtb \
	apq8094-v2-fluid.dtb

dtb-$(CONFIG_ARCH_MSM8992) += msm8992-sim.dtb \
	msm8992-rumi.dtb

DTB_NAMES := $(subst $\",,$(CONFIG_BUILD_ARM_APPENDED_DTB_IMAGE_NAMES))
ifneq ($(DTB_NAMES),)
DTB_LIST := $(addsuffix .dtb,$(DTB_NAMES))
else
DTB_LIST := $(dtb-y)
endif

targets += dtbs
targets += $(addprefix ../, $(DTB_LIST))
endif

$(obj)/../../%.dtb: $(src)/%.dts FORCE
	$(call if_changed_dep,dtc)

dtbs: $(addprefix $(obj)/../../,$(DTB_LIST))

clean-files := *.dtb

